# Generated by Django 3.1.1 on 2020-10-08 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_person_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='group_name',
        ),
    ]
