# Generated by Django 3.1.1 on 2020-10-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_group_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description_slug',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
